###########################
# @author Elias De Hondt  #
# @since 18/11/2024       #
###########################
# sudo docker login registry.gitlab.com
# sudo docker compose -f compose.yaml pull
# sudo docker compose -f compose.yaml up -d
# sudo docker ps
# sudo docker compose -f compose.yaml logs -f
# sudo docker compose -f compose.yaml down
# sudo docker volume rm team20_compose_db_data
name: team20_compose

# Services Definition
services:
  # Backend service
  backend:
    image: registry.gitlab.com/kdg-ti/integratieproject-2/2024-2025/team20/backend-game-service/spring-backend:latest
    pull_policy: always
    environment:
      KEYCLOAK_URL: http://localhost:8080/realms/MonopolyRealm
    network_mode: "host"
    extra_hosts:
      - "frontend:127.0.0.1"
      - "ai:127.0.0.1"
  # Frontend service
  frontend:
    image: registry.gitlab.com/kdg-ti/integratieproject-2/2024-2025/team20/frontend/react-frontend-isb-local:latest
    pull_policy: always
    environment:
      VITE_API_BASE_URL: http://backend:8081/
      VITE_KEYCLOAK_CLIENT_ID: 123
      VITE_KEYCLOAK_REALM: realm
      VITE_KEYCLOAK_URL: http://localhost:8080
      VITE_DEFAULT_BACKGROUND_URL: https://storage.googleapis.com/team-20-monopoly-ip2-pulic-assets/store-item/content/city.png
      VITE_DEFAULT_SOUND_URL: https://storage.googleapis.com/team-20-monopoly-ip2-pulic-assets/store-item/content/main-theme.mp3
    network_mode: "host"
    extra_hosts:
      - "backend:127.0.0.1"
      - "ai:127.0.0.1"
  # AI service
#  ai:
#    image: registry.gitlab.com/kdg-ti/integratieproject-2/2024-2025/team20/backend-ai-service/python-ai:latest
#    network_mode: "host"
#    extra_hosts:
#      - "frontend:127.0.0.1"
#      - "backend:127.0.0.1"
  # Keycloak service
  keycloak:
    image: bitnami/keycloak:25
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
  # Postgres service
  postgres:
    image: postgres:16
    pull_policy: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mono_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    configs:
      - source: keycloak.sql
        target: /docker-entrypoint-initdb.d/keycloak.sql
    volumes:
      - db_data:/var/lib/postgresql/data

# Configs Definition
configs:
  keycloak.sql:
    content: |
      CREATE ROLE keycloak WITH
        LOGIN
        NOSUPERUSER
        NOCREATEDB
        NOCREATEROLE
        INHERIT
        NOREPLICATION
        NOBYPASSRLS
        CONNECTION LIMIT -1
        PASSWORD 'keycloak';

      CREATE DATABASE keycloak
          WITH
          OWNER = keycloak
          ENCODING = 'UTF8'
          LOCALE_PROVIDER = 'libc'
          CONNECTION LIMIT = -1
          IS_TEMPLATE = False;

# Volumes Definition
volumes:
  db_data: