###########################
# @author Elias De Hondt  #
# @since 18/11/2024       #
###########################
# Description: This file is used to store the credentials for the pods.
# Usage: kubectl apply -f credentials.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-credentials
type: Opaque
data:
  username: YWRtaW4= # admin
  password: MTIz # 123
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: ZGF0YWJhc2UtdXNlcg== # database-user
  password: MTIz # 123
  url: amRiYzpwb3N0Z3Jlc3FsOi8vbG9jYWxob3N0OjU0MzIvY2F0YW5fZGI=
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
type: Opaque
data:
  username: YWRtaW4= # admin
  password: MTIz # 123
---