###########################
# @author Elias De Hondt  #
# @since 18/11/2024       #
###########################
# Description: This pod is used to run React Frontend.
# Usage: kubectl apply -f pod1.yaml
---