###########################
# @author Elias De Hondt  #
# @since 18/11/2024       #
###########################
# Description: This pod is used to run React Frontend.
# Usage: kubectl apply -f pod1.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  labels:
    app: react-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: "registry.gitlab.com" # Image path changed by the end user when following the manual
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: "http://spring-backend-service:80"
            - name: KEYCLOAK_URL
              value: "http://keycloak-iam-service:80"
            - name: KYCLOAK_REALM
              value: "realm"
            - name: KEYCLOAK_CLIENT_ID
              value: "123"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 3000 # Internal port in the container
---
