###########################
# @author Elias De Hondt  #
# @since 18/11/2024       #
###########################
# Description: This pod is used to run Spring Backend and SQL proxy.
# Usage: kubectl apply -f pod3.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
  labels:
    app: spring-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
        - name: spring-backend
          image: "registry.gitlab.com" # Image path changed by the end user when following the manual
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: DB_NAME
              value: "database-postgresql"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: AI_URL
              value: "http://python-runtime-service:5000"
            - name: DB_URL
              value: "jdbc:postgresql://localhost:5432/database-postgresql"
          resources:
            limits:
                memory: "4Gi"
                cpu: "2"
            requests:
                memory: "2Gi"
                cpu: "1"
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
          args:
            - "--private-ip"
            - "--auto-iam-authn"
            - "--structured-logs"
            - "--port=5432"
            - "ProjectId:us-central1:cloud-sql-instance" # ProjectId changed by the end user when following the manual
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: sql-auth-proxy-volume
              mountPath: /secrets/
              readOnly: true
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: gitlab-registry
      volumes:
        - name: sql-auth-proxy-volume
          secret:
            secretName: sql-auth-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: spring-backend-service
spec:
  selector:
    app: spring-backend
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 8081 # Internal port in the container
  type: ClusterIP
---