###########################
# @author Elias De Hondt  #
# @since 18/11/2024       #
###########################
# Description: This pod is used to run Spring Backend and SQL proxy.
# Usage: kubectl apply -f pod3.yaml
---