###########################
# @author Elias De Hondt  #
# @since 18/11/2024       #
###########################
# Description: This pod is used for monitoring the health of the kubernetes cluster with the help of the grafana.
# Usage: kubectl apply -f pod5.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'blackbox'
        metrics_path: /metrics
        static_configs:
          - targets: ['localhost:9115']
      - job_name: 'blackbox-http'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
              - https://keycloak.teamx.eliasdh.com
              - https://www.teamx.eliasdh.com
              - https://api.teamx.eliasdh.com
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: localhost:9115
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://localhost:9090",
                "version": 1
            }
        ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
data:
  provider.yaml: |-
    {
      "apiVersion": 1,
      "providers": [
        {
          "name": "Default",
          "folder": "Services",
          "type": "file",
          "options": {
            "path": "/var/lib/grafana/dashboards"
          }
        }
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  status.json: |-
    {
        "annotations": {
            "list": [
            {
              "builtIn": 1,
              "datasource": {
                "type": "grafana",
                "uid": "-- Grafana --"
              },
              "enable": true,
              "hide": true,
              "iconColor": "rgba(0, 211, 255, 1)",
              "name": "Annotations & Alerts",
              "type": "dashboard"
            }
          ]
        },
        "editable": true,
        "fiscalYearStartMonth": 0,
        "graphTooltip": 0,
        "id": 4,
        "links": [],
        "panels": [
          {
            "datasource": {
              "type": "prometheus",
              "uid": "P1809F7CD0C75ACF3"
            },
            "fieldConfig": {
              "defaults": {
                "color": {
                  "fixedColor": "text",
                  "mode": "fixed"
                },
                "custom": {
                  "align": "auto",
                  "cellOptions": {
                    "type": "color-text"
                  },
                  "filterable": false,
                  "inspect": false
                },
                "mappings": [
                  {
                    "options": {
                      "from": 200,
                      "result": {
                        "color": "green",
                        "index": 0,
                        "text": "UP"
                      },
                      "to": 403
                    },
                    "type": "range"
                  },
                  {
                    "options": {
                      "from": 404,
                      "result": {
                        "color": "red",
                        "index": 1,
                        "text": "DOWN"
                      },
                      "to": 600
                    },
                    "type": "range"
                  }
                ],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    }
                  ]
                }
              },
              "overrides": []
            },
            "gridPos": {
              "h": 7,
              "w": 24,
              "x": 0,
              "y": 0
            },
            "id": 2,
            "options": {
              "cellHeight": "sm",
              "footer": {
                "countRows": false,
                "enablePagination": false,
                "fields": "",
                "reducer": [
                  "sum"
                ],
                "show": false
              },
              "showHeader": true,
              "sortBy": [
                {
                  "desc": false,
                  "displayName": "instance"
                }
              ]
            },
            "pluginVersion": "11.4.0",
            "targets": [
              {
                "editorMode": "code",
                "expr": "sum(probe_http_status_code) without (__name__,job)",
                "format": "table",
                "legendFormat": "__auto",
                "range": true,
                "refId": "A"
              }
            ],
            "title": "Current state",
            "transformations": [
              {
                "id": "renameByRegex",
                "options": {
                  "regex": "(instance)",
                  "renamePattern": "Target"
                }
              },
              {
                "id": "renameByRegex",
                "options": {
                  "regex": "Value",
                  "renamePattern": "State"
                }
              },
              {
                "id": "renameByRegex",
                "options": {
                  "regex": "Time",
                  "renamePattern": "Last checked"
                }
              }
            ],
            "type": "table"
          },
          {
            "datasource": {
              "type": "prometheus",
              "uid": "P1809F7CD0C75ACF3"
            },
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "axisBorderShow": false,
                  "axisCenteredZero": false,
                  "axisColorMode": "text",
                  "axisGridShow": true,
                  "axisLabel": "",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "barWidthFactor": 0.6,
                  "drawStyle": "line",
                  "fillOpacity": 0,
                  "gradientMode": "none",
                  "hideFrom": {
                    "legend": false,
                    "tooltip": false,
                    "viz": false
                  },
                  "insertNulls": false,
                  "lineInterpolation": "linear",
                  "lineStyle": {
                    "fill": "solid"
                  },
                  "lineWidth": 1,
                  "pointSize": 5,
                  "scaleDistribution": {
                    "type": "linear"
                  },
                  "showPoints": "auto",
                  "spanNulls": false,
                  "stacking": {
                    "group": "A",
                    "mode": "none"
                  },
                  "thresholdsStyle": {
                    "mode": "off"
                  }
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    }
                  ]
                }
              },
              "overrides": []
            },
            "gridPos": {
              "h": 9,
              "w": 24,
              "x": 0,
              "y": 7
            },
            "id": 1,
            "interval": "30s",
            "options": {
              "legend": {
                "calcs": [],
                "displayMode": "list",
                "placement": "bottom",
                "showLegend": true
              },
              "tooltip": {
                "mode": "single",
                "sort": "none"
              }
            },
            "pluginVersion": "11.4.0",
            "targets": [
              {
                "editorMode": "code",
                "expr": "sum(probe_http_status_code) without (__name__,job)",
                "legendFormat": "__auto",
                "range": true,
                "refId": "A"
              }
            ],
            "timeFrom": "6h",
            "title": "Status code over time",
            "type": "timeseries"
          }
        ],
        "preload": false,
        "refresh": "30s",
        "schemaVersion": 40,
        "tags": [],
        "templating": {
          "list": []
        },
        "time": {
          "from": "now",
          "to": "now"
        },
        "timepicker": {},
        "timezone": "browser",
        "title": "Service Status",
        "uid": "fe7hz34qa94aob",
        "version": 4,
        "weekStart": ""
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring 
  labels:
    app: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: monitoring-credentials
                  key: username
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: monitoring-credentials
                  key: password
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              readOnly: false
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-dashboard-provider
            - mountPath: /var/lib/grafana/dashboards
              name: grafana-dashboards
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: prometheus-server-conf
              mountPath: /etc/prometheus
        - name: blackbox-exporter
          image: prom/blackbox-exporter:latest
          ports:
            - containerPort: 9115
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
        - name: grafana-dashboards
          configMap:
            defaultMode: 420
            name: grafana-dashboards
        - name: grafana-dashboard-provider
          configMap:
            defaultMode: 420
            name: grafana-dashboard-provider
        - name: prometheus-server-conf
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  labels:
    app: monitoring
spec:
  selector:
    app: monitoring
  ports:
    - name: grafana
      protocol: TCP
      port: 80 # Port used by the Ingress
      targetPort: 3000 # Grafana runs internally on port 3000
---