##############################
# @author Wolf Van den Zegel #
# @since 04/01/2025          #
##############################
---
elasticsearchHosts: "http://elasticsearch-master:9200"
replicas: 1
extraEnvs:
  - name: "NODE_OPTIONS"
    value: "--max-old-space-size=1800"
envFrom: []
secretMounts: []
hostAliases: []
image: "docker.elastic.co/kibana/kibana"
imageTag: "8.16.0"
imagePullPolicy: "IfNotPresent"
labels: {}
podAnnotations:
  {}
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
protocol: http
serverHost: "0.0.0.0"
healthCheckPath: "/app/kibana"
# kibanaConfig:
#    kibana.yml: |
#      server.host: "0.0.0.0"
#      elasticsearch.hosts: ["http://elasticsearch-master:9200"]
#      xpack.encryptedSavedObjects.encryptionKey: "9h3eVT7uPT3jjXgYHDm9OPGuVPAbrJv/5iRGx5TaxsQ="
#      xpack.security.encryptionKey: "Gj8P0AJJbrpF88I37xUCstdfLocYDzdbef9dkjyG1Ik="
#      xpack.reporting.encryptionKey: "qlT3u+Y+tzATyf3z4TEuayUHRUz1N3fZFEteyDAxC90="
#      xpack.fleet.enabled: false
podSecurityContext:
  fsGroup: 1000
securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000
serviceAccount: ""
priorityClassName: ""
httpPort: 5601
extraVolumes:
  []
extraVolumeMounts:
  []
extraContainers: ""
extraInitContainers: ""
updateStrategy:
  type: "Recreate"
service:
  # type: ClusterIP
  loadBalancerIP: ""
  port: 5601
  nodePort: ""
  labels: {}
  annotations:
    {}
  loadBalancerSourceRanges:
    []
  httpPortName: http
ingress:
  enabled: true
  className: "nginx"
  pathtype: ImplementationSpecific
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: elk.team5.vdz-homelab.com
      paths:
        - path: /
  tls:
    - secretName: elk-tls
      hosts:
        - elk.team5.vdz-homelab.com
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
imagePullSecrets: []
nodeSelector: {}
tolerations: []
affinity: {}
nameOverride: ""
fullnameOverride: ""
lifecycle:
  {}
