##############################
# @author Wolf Van den Zegel #
# @since 04/01/2025          #
##############################
imageTag: "8.16.0"
logstashConfig:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.hosts: ["https://elasticsearch-master:9200"]
    xpack.monitoring.elasticsearch.ssl.certificate_authority: "/usr/share/logstash/config/certs/ca.crt"
    config.support_escapes: true
logstashPipeline:
  logstash.conf: |
    input {
      rabbitmq {
        host => "rabbitmq-service"
        queue => "user-profile"
        durable => true
        user => "${RABBITMQ_USERNAME}"
        password => "${RABBITMQ_PASSWORD}"
        port => 5672
        codec => json
        add_field => { "[@metadata][index]" => "user-profile-index" }
      }

      rabbitmq {
        host => "rabbitmq-service"
        queue => "user-activity"
        durable => true
        user => "${RABBITMQ_USERNAME}"
        password => "${RABBITMQ_PASSWORD}"
        port => 5672
        codec => json
        add_field => { "[@metadata][index]" => "user-activity-index" }
      }

      rabbitmq {
        host => "rabbitmq-service"
        queue => "game-sessions"
        durable => true
        user => "${RABBITMQ_USERNAME}"
        password => "${RABBITMQ_PASSWORD}"
        port => 5672
        codec => json
        add_field => { "[@metadata][index]" => "game-sessions-index" }
      }

      rabbitmq {
        host => "rabbitmq-service"
        queue => "game-bets"
        durable => true
        user => "${RABBITMQ_USERNAME}"
        password => "${RABBITMQ_PASSWORD}"
        port => 5672
        codec => json
        add_field => { "[@metadata][index]" => "game-bets-index" }
      }

      rabbitmq {
        host => "rabbitmq-service"
        queue => "game-decisions"
        durable => true
        user => "${RABBITMQ_USERNAME}"
        password => "${RABBITMQ_PASSWORD}"
        port => 5672
        codec => json
        add_field => { "[@metadata][index]" => "game-decisions-index" }
      }

      rabbitmq {
        host => "rabbitmq-service"
        queue => "game-results"
        durable => true
        user => "${RABBITMQ_USERNAME}"
        password => "${RABBITMQ_PASSWORD}"
        port => 5672
        codec => json
        add_field => { "[@metadata][index]" => "game-results-index" }
      }
    }
    filter {
      mutate {
        remove_field => ["@timestamp", "@version", "host", "event"]
      }
    }
    output {
      elasticsearch {
        hosts => ["https://elasticsearch-master:9200"]
        user => "${ELASTIC_USERNAME}"
        password => "${ELASTIC_PASSWORD}"
        ssl_certificate_authorities => "/usr/share/logstash/config/certs/ca.crt"
        index => "%{[@metadata][index]}"
      }
      stdout { codec => rubydebug }
    }
resources:
  limits:
    memory: 2Gi
    cpu: 1
  requests:
    memory: 1Gi
    cpu: 500m
readinessProbe:
  exec:
    command:
      - curl
      - --cacert
      - /usr/share/elasticsearch/config/certs/ca/ca.crt
      - https://127.0.0.1:9200
extraVolumes: |
  - name: elasticsearch-certificates
    secret:
      secretName: elasticsearch-certificates
extraVolumeMounts: |
  - name: elasticsearch-certificates
    mountPath: /usr/share/logstash/config/certs
    readOnly: true
extraEnvVars:
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: RABBITMQ_USERNAME
    valueFrom:
      secretKeyRef:
        name: rabbitmq-credentials
        key: username
  - name: RABBITMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        name: rabbitmq-credentials